# Generated by Django 3.0.2 on 2020-01-11 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blue_team_1', to='heroes.Hero')),
                ('hero_10', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='red_team_5', to='heroes.Hero')),
                ('hero_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blue_team_2', to='heroes.Hero')),
                ('hero_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blue_team_3', to='heroes.Hero')),
                ('hero_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blue_team_4', to='heroes.Hero')),
                ('hero_5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blue_team_5', to='heroes.Hero')),
                ('hero_6', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='red_team_1', to='heroes.Hero')),
                ('hero_7', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='red_team_2', to='heroes.Hero')),
                ('hero_8', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='red_team_3', to='heroes.Hero')),
                ('hero_9', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='red_team_4', to='heroes.Hero')),
            ],
        ),
    ]
