# Generated by Django 3.0.2 on 2020-01-13 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_record_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='owner',
        ),
    ]
